from pathlib import Path
import shutil

from docx import Document
from docx.oxml import OxmlElement
from docx.text.paragraph import Paragraph
from docx.shared import Pt, RGBColor


PAPER = Path(r"D:\NLG\Paper.docx")
BACKUP = Path(r"D:\NLG\Paper_before_coupled_proper_noun_section.docx")


def set_run_format(run, bold=False):
    run.font.name = "Calibri"
    run.font.size = Pt(12)
    run.font.color.rgb = RGBColor(0, 0, 0)
    run.bold = bold


def set_paragraph_format(paragraph, style_name):
    paragraph.style = style_name
    for run in paragraph.runs:
        set_run_format(run, bold=style_name.startswith("Heading"))


def insert_paragraph_after(paragraph, text="", style=None):
    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if style is not None:
        new_para.style = style
    run = new_para.add_run(text)
    set_run_format(run, bold=(style is not None and style.startswith("Heading")))
    return new_para


def main():
    if not BACKUP.exists():
        shutil.copy2(PAPER, BACKUP)

    doc = Document(PAPER)

    for paragraph in doc.paragraphs:
        text = paragraph.text.strip()
        if text.startswith("A further extension concerns the treatment of numeral quantifiers"):
            set_paragraph_format(paragraph, "Normal")
        elif text.startswith("To support numeral quantifiers"):
            set_paragraph_format(paragraph, "Normal")
        elif text == "Evaluation of the Quantifier Extension":
            set_paragraph_format(paragraph, "Heading 1")

    background = next(
        paragraph for paragraph in doc.paragraphs
        if paragraph.text.strip() == "Background and Related Work"
    )
    impl_body_2 = insert_paragraph_after(
        background,
        "The XML design was extended by introducing a propernouncompound element inside the normal noun phrase position, with relation=\"mariyu\". The element contains two proper-noun roots, one marked role=\"first\" and the other marked role=\"final\". For the first implementation, the realization rule is deliberately narrow: a first proper noun ending in short final a is converted to its combining form by changing final a to A, while other first nouns remain unchanged. The final proper noun is realized as plural, including the proper-name pattern rAmudu -> rAmulu. Thus the input preserves lexical roots such as sIwa and rAmudu, and the output sIwA rAmulu is generated by the realization pipeline rather than by placing the surface form directly in the XML.",
        "Normal",
    )
    impl_body_1 = insert_paragraph_after(
        background,
        "A second extension handles coupled proper-noun expressions that express the relation mariyu without an overt surface conjunction. Descriptive Telugu grammar records examples such as sIwa + rAmudu -> sIwA rAmulu, subbarAvu + suMxaraM -> subbarAvu suMxarAlu, and britan + ameVrikA -> britan amerikAlu. These forms cannot be represented cleanly by treating the first name as an ordinary subject and the second name as an ordinary complement, because the two names together form one coordinated proper-noun expression. The extension therefore treats the construction as a single noun phrase with an internal relation.",
        "Normal",
    )
    insert_paragraph_after(
        background,
        "Extension for Coupled Proper Noun Expressions",
        "Heading 1",
    )

    quant_eval_body = next(
        paragraph for paragraph in doc.paragraphs
        if paragraph.text.strip().startswith("The same evaluation also confirms")
    )
    eval_body = insert_paragraph_after(
        quant_eval_body,
        "The coupled proper-noun extension was evaluated with three Krishnamurti-based examples. The system generates sIwA rAmulu from roots sIwa and rAmudu, subbarAvu suMxarAlu from subbarAvu and suMxaraM, and britan amerikAlu from britan and amerikA. These examples are represented with propernouncompound relation=\"mariyu\" rather than by pre-inflecting the words in the XML. The original fourteen evaluation examples and the earlier Krishnamurti noun and quantifier examples were rerun after this extension, and their outputs remained unchanged.",
        "Normal",
    )
    insert_paragraph_after(
        quant_eval_body,
        "Evaluation of the Coupled Proper Noun Extension",
        "Heading 1",
    )

    for paragraph in doc.paragraphs:
        if paragraph.style.name == "Normal":
            for run in paragraph.runs:
                set_run_format(run)
        elif paragraph.style.name.startswith("Heading"):
            for run in paragraph.runs:
                set_run_format(run, bold=True)

    doc.save(PAPER)
    print(f"Updated {PAPER}")
    print(f"Backup {BACKUP}")


if __name__ == "__main__":
    main()
